name: Deploy Project

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 배포 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:22

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Get SSH Key and Set Permissions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy Using RSYNC
        run: |
          rsync -avz --exclude=node_modules --exclude=.git --exclude=.github --delete \
          -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa" ./ \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/ohgnoy

      - name: Restart Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /var/www/ohgnoy
          npm install
          pm2 describe ohgnoy > /dev/null || pm2 start dist/app.js --name ohgnoy
          pm2 restart ohgnoy
          exit
          EOF